---
title: "Next word prediction using Word2Vec"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Next word prediction using Word2Vec}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
oldopt <- options(digits = 2, width = 100)
```

```{r setup}
library(aimat)
set.seed(42)
```

Børnebogen ligger som en vektor:
```{r}
length(bog)
bog[1:30]
```

Word2vec med dimension 3 og kontekst +/-1:
```{r cache=TRUE}
bog_w2v <- w2v(bog, win = 1, hidden_dim = 3, epochs = 1000, learning_rate = 0.02, verbose = 100)
```

Next word prediction data genereres:
```{r}
bog_data <- nwp_make_word_data(corpus = bog, context_size = 6, w2v = bog_w2v)
```

Ordene i data:
```{r}
dim(bog_data$words)
head(bog_data$words)
```

Numeriske data:
```{r}
dim(bog_data$numeric)
head(bog_data$numeric)
```

Træn et neuralt netværk:
```{r cache=TRUE}
bog_nwp <- nn_fun(target ~ ., data = bog_data$numeric, n_hidden = c(15,0), iter = 5000, eta = 0.002, scale = TRUE)
```

Prædiktion af næste ord (i træningsdata):
```{r}
pred <- predict(bog_nwp, newdata = bog_data$numeric[1:20,], type = "class")
```

Nye forudsigelser:
```{r}
ny <- bog_data$words[1:20,]
ny[,ncol(ny)] <- pred
ny
```

## Uden Word2Vec

```{r}
bog_vocab <- unique(bog)
W1 <- fibonacci_sphere(length(bog_vocab))
bog_data_fib <- nwp_make_word_data(corpus = bog, context_size = 6, w2v = list(W1 = W1, W2 = NULL, vocab = bog_vocab))
bog_nwp_fib <- nn_fun(target ~ ., data = bog_data_fib$numeric, n_hidden = c(15,0), iter = 2000, eta = 0.001, scale = TRUE)
```


Prædiktion af næste ord (i træningsdata):
```{r}
pred_fib <- predict(bog_nwp_fib, newdata = bog_data_fib$numeric[1:20,], type = "class")
```

Nye forudsigelser:
```{r}
ny_fib <- bog_data_fib$words[1:20,]
ny_fib[,ncol(ny_fib)] <- pred_fib
ny_fib
```
